### ISSUE TITLE
Add optional side panel

### ISSUE THREAD

**Issue by jhansche** [myYearbook/jira-gerrit-plugin#1]
Consider moving (or giving the option of placement) the reviews to be a side panel (like where the "People", "Dates", "Drag and Drop" boxes are in the top-right of a JIRA issue).

The current placement as an issue tab panel makes it secondary to other activity on the ticket (most importantly, Comments).  And the "All" tab is often too cluttered to become the primary tab  for this.  Would be more appropriate to allow the reviews to be listed in the side panel instead, so it doesn't matter which issue tab panel is currently open.

**Comment by dallasgutauckis** [comment]
+1

**Comment by jhansche** [comment]
This is complete in version 2.0, including a left-side web panel
